config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'product#index'
  get '/products' => 'product#product_list'
  get '/crawls' => 'product#product_crawl'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  enum product_type: { mobile: 0, men_footwear: 1, women_footwear: 2, women_sandal: 3, beauty_grooming: 4 }
  validates :url, :product_type, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @product_categories = Product.product_types
  end

  def product_list
    @product_lists = Scrape::Main.new(params[:key]).list.paginate(page: params[:page], per_page: 10)
    flash[:error] = 'No products found!!!' unless @product_lists.present?
  end

  def product_crawl
    @product_lists = Scrape::Main.new(params[:key]).crawl
    flash[:success] = 'Product successfully crawled!!!' if @product_lists.present?
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
  def find_product_list(key)
    case key
    when 'mobile'
      'Mobile'
    when 'men_footwear'
      'Men Footwear'
    when 'women_footwear'
      'Women Footwear'
    when 'women_sandal'
      'Women Sandal'
    when 'women_shoe'
      'Women Shoe'
    when 'beauty_grooming'
      'Beauty Grooming'
    end
  end

  def product_exists?(key)
    Scrape::Main.new(key).list.present?
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_without_login_header.html.erb
<nav  class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Scrapping", root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scraping</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/without_login_header'%>
    <%= render partial: '/layouts/flash' unless flash.empty? %>
    <section class='login_wrapper'>
      <div class= 'container'>
        <%= yield %>
      </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/product/index.html.erb
<% if @product_categories.present? %>
  <h1 style="text-align: center;">Available Products !!!</h1>
<table>
  <tr>
    <th>Name</th>
    <th colspan="2">Action</th>
  </tr>
  <% @product_categories.keys.each do |key| %>
    <tr>
      <td><%= find_product_list(key) %></td>
      <td><%= link_to 'List', products_path(key: key), class: 'btn btn-success' %></td>
      <td><%= link_to 'Crawl', crawls_path(key: key), class: 'btn btn-success' unless product_exists?(key) %></td>
    </tr>
  <% end %>
</table>
<% else %>
  <h1 style="text-align: center;">There is no products available !!!</h1>
<% end %>

app/views/product/product_list.html.erb
<% if @product_lists.present? %>
  <h1 style="text-align: center;"><%= find_product_list(params[:key])%> list!!!</h1>
  <table>
    <tr>
      <% unless params[:key] == 'mobile' %>
        <th>Brand</th>
        <th>Combo</th>
      <% else %>
        <th>Name</th>
        <th>Ratings</th>
        <th>Reviews</th>
      <% end %>
      <th>Price</th>
      <th>Url</th>
    </tr>
    <% @product_lists.each do |product| %>
      <tr>
        <% unless params[:key] == 'mobile' %>
          <td><%= product.brand %></td>
          <td><%= product.combo %></td>
        <% else %>
          <td><%= product.name %></td>
          <td><%= product.rating %></td>
          <td><%= product.review %></td>
        <% end %>
        <td><%= product.price %></td>
        <td><%= link_to "See full details", "#{product.url}", target: '_blank', class: 'btn btn-success' %></td>
      </tr>
    <% end %>
  </table><br>
  <div class = "digg_pagination" >
    <%= will_paginate @product_lists %>
  </div><br>
<% end %>
<%= link_to 'Back', root_path, class: 'btn btn-primary' %>